import {
  AnalyticsSummary,
  AppInfo,
  DiscoveredProfile,
  HistoryPageResult,
  SecurityState,
  VisitListItem,
} from '../types';

export const mockProfiles: DiscoveredProfile[] = [
  {
    source_id: 1,
    browser: 'chrome',
    profile_id: 'Default',
    profile_name: '个人工作 (Default)',
    history_path: 'C:\\Users\\MockUser\\AppData\\Local\\Google\\Chrome\\User Data\\Default\\History',
    history_size_bytes: 14589000,
    last_modified: Date.now() - 3600000,
    is_running: false,
  },
  {
    source_id: 2,
    browser: 'edge',
    profile_id: 'Default',
    profile_name: '日常浏览 (Profile 1)',
    history_path: 'C:\\Users\\MockUser\\AppData\\Local\\Microsoft\\Edge\\User Data\\Default\\History',
    history_size_bytes: 8420000,
    last_modified: Date.now() - 7200000,
    is_running: false,
  },
  {
    source_id: 3,
    browser: 'brave',
    profile_id: 'Default',
    profile_name: '开发测试 (Default)',
    history_path: 'C:\\Users\\MockUser\\AppData\\Local\\BraveSoftware\\Brave-Browser\\User Data\\Default\\History',
    history_size_bytes: 5120000,
    last_modified: Date.now() - 14400000,
    is_running: false,
  },
];

export const mockVisits: VisitListItem[] = [
  {
    id: 1,
    url_id: 101,
    visit_time: Date.now() - 120000,
    title: 'GitHub: Let’s build from here · GitHub',
    url: 'https://github.com',
    domain: 'github.com',
    browser: 'chrome',
    profile: 'Default',
    visit_duration: 340,
    transition: 0,
    is_favorite: true,
  },
  {
    id: 2,
    url_id: 102,
    visit_time: Date.now() - 480000,
    title: 'Rust Programming Language - Performance, Reliability, Productivity',
    url: 'https://www.rust-lang.org',
    domain: 'rust-lang.org',
    browser: 'chrome',
    profile: 'Default',
    visit_duration: 520,
    transition: 0,
  },
  {
    id: 3,
    url_id: 103,
    visit_time: Date.now() - 1500000,
    title: 'MDN Web Docs - Resources for developers, by developers',
    url: 'https://developer.mozilla.org/en-US/',
    domain: 'developer.mozilla.org',
    browser: 'edge',
    profile: 'Default',
    visit_duration: 210,
    transition: 1,
  },
  {
    id: 4,
    url_id: 104,
    visit_time: Date.now() - 3600000,
    title: 'Tauri 2.0 - Build smaller, faster, and more secure desktop applications',
    url: 'https://v2.tauri.app',
    domain: 'v2.tauri.app',
    browser: 'chrome',
    profile: 'Default',
    visit_duration: 680,
    transition: 0,
    is_favorite: true,
  },
  {
    id: 5,
    url_id: 105,
    visit_time: Date.now() - 7200000,
    title: 'SQLite Documentation & Architecture Overview',
    url: 'https://www.sqlite.org/docs.html',
    domain: 'sqlite.org',
    browser: 'brave',
    profile: 'Default',
    visit_duration: 410,
    transition: 0,
  },
  {
    id: 6,
    url_id: 106,
    visit_time: Date.now() - 10800000,
    title: 'React Documentation - The library for web and native user interfaces',
    url: 'https://react.dev',
    domain: 'react.dev',
    browser: 'edge',
    profile: 'Default',
    visit_duration: 310,
    transition: 0,
  },
];

export const mockHistoryPage: HistoryPageResult = {
  items: mockVisits,
  next_cursor_time: null,
  next_cursor_id: null,
  has_more: false,
};

export const mockAnalytics: AnalyticsSummary = {
  total_visits: 12450,
  unique_urls: 3820,
  unique_domains: 642,
  active_days: 28,
  revisit_rate: 68.4,
  domain_ranking: [
    { domain: 'github.com', count: 2450 },
    { domain: 'developer.mozilla.org', count: 1540 },
    { domain: 'rust-lang.org', count: 1120 },
    { domain: 'v2.tauri.app', count: 890 },
    { domain: 'sqlite.org', count: 760 },
    { domain: 'react.dev', count: 650 },
  ],
  browser_breakdown: [
    { name: 'chrome', count: 7200, percent: 57.8 },
    { name: 'edge', count: 3650, percent: 29.3 },
    { name: 'brave', count: 1600, percent: 12.9 },
  ],
  hourly_distribution: [
    { hour: 0, count: 45 }, { hour: 1, count: 12 }, { hour: 2, count: 5 }, { hour: 3, count: 2 },
    { hour: 4, count: 1 }, { hour: 5, count: 3 }, { hour: 6, count: 18 }, { hour: 7, count: 56 },
    { hour: 8, count: 140 }, { hour: 9, count: 320 }, { hour: 10, count: 410 }, { hour: 11, count: 390 },
    { hour: 12, count: 210 }, { hour: 13, count: 280 }, { hour: 14, count: 430 }, { hour: 15, count: 480 },
    { hour: 16, count: 520 }, { hour: 17, count: 460 }, { hour: 18, count: 310 }, { hour: 19, count: 260 },
    { hour: 20, count: 380 }, { hour: 21, count: 420 }, { hour: 22, count: 310 }, { hour: 23, count: 150 },
  ],
  daily_trend: [
    { date: '09-08', count: 380 },
    { date: '09-09', count: 420 },
    { date: '09-10', count: 510 },
    { date: '09-11', count: 395 },
    { date: '09-12', count: 460 },
    { date: '09-13', count: 430 },
    { date: '09-14', count: 475 },
  ],
  top_search_queries: [
    { query: 'rust async stream', engine: 'Google', count: 42, last_searched_at: Date.now() - 3600000 },
    { query: 'tauri 2 bundle icon', engine: 'Google', count: 28, last_searched_at: Date.now() - 7200000 },
    { query: 'sqlite fts5 ranking', engine: 'Bing', count: 19, last_searched_at: Date.now() - 14400000 },
  ],
  weekly_heatmap: [
    { day_of_week: 1, hour: 10, count: 85 },
    { day_of_week: 1, hour: 14, count: 92 },
    { day_of_week: 2, hour: 11, count: 78 },
    { day_of_week: 3, hour: 15, count: 110 },
    { day_of_week: 4, hour: 16, count: 95 },
    { day_of_week: 5, hour: 14, count: 102 },
  ],
  forgotten_gems: [
    {
      url_id: 105,
      title: 'SQLite Documentation & Architecture Overview',
      url: 'https://www.sqlite.org/docs.html',
      domain: 'sqlite.org',
      total_visits: 12,
      last_visit_time: Date.now() - 86400000 * 20,
    },
  ],
  period_comparison: {
    current_count: 3120,
    previous_count: 2890,
    growth_rate: 7.96,
  },
};

export const mockAppInfo: AppInfo = {
  app_dir: 'C:\\Users\\MockUser\\AppData\\Local\\com.browsory.desktop',
  db_path: 'C:\\Users\\MockUser\\AppData\\Local\\com.browsory.desktop\\browsory.db',
  db_size_bytes: 28450120,
  temp_dir: 'C:\\Users\\MockUser\\AppData\\Local\\Temp\\browsory',
  logs_dir: 'C:\\Users\\MockUser\\AppData\\Local\\com.browsory.desktop\\logs',
};

export const mockSecurityState: SecurityState = {
  pin_enabled: false,
  auto_lock_minutes: 15,
  lock_on_minimize: false,
  lock_on_sleep: true,
  is_locked_out: false,
  lockout_remaining_secs: 0,
};
